name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Version officielle et automatisée pour Solar2D :
    - name: Build Android APK with Solar2D Action
      uses: cyber_folks/solar2d-build-action@v1
      with:
        recipe-path: 'recipe.lua'

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CCode-Lite-APK
        path: builds/CCode-Lite.apk
        
