name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download and Setup Solar2D Release
      run: |
        # On utilise wget avec des options pour forcer le téléchargement du vrai fichier
        wget "https://github.com/coronalabs/corona/releases/download/3712/Solar2D-Linux-3712.tar.gz" -O solar2d.tar.gz
        
        # On vérifie la taille pour être sûr (si c'est vide ou minuscule, ça s'arrêtera ici)
        ls -lh solar2d.tar.gz
        
        # Extraction
        tar -xzf solar2d.tar.gz
        
        # On renomme et on donne les droits
        mv Solar2D-Linux-3712 solar2d-cli
        chmod +x ./solar2d-cli/resources/Solar2D-Builder

    - name: Build APK via Solar2D
      run: |
        mkdir -p builds
        ./solar2d-cli/resources/Solar2D-Builder build recipe.lua

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CCode-Lite-APK
        path: builds/CCode-Lite.apk
        
